name: ateez_lyrics
description: ATEEZ Lyrics

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_widget_from_html_core: ^0.9.0+2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/misc/
    - assets/images/cover_art/
    - assets/lyrics/spin_off_from_the_witness/
    - assets/lyrics/the_world_ep_paradigm/
    - assets/lyrics/the_world_ep_1_movement/
    - assets/lyrics/beyond_zero/
    - assets/lyrics/fever_pt_1/
    - assets/lyrics/fever_pt_2/
    - assets/lyrics/fever_pt_3/
    - assets/lyrics/dreamers/
    - assets/lyrics/fever_epilogue/
    - assets/lyrics/treasure_ep_1/
    - assets/lyrics/treasure_ep_2/
    - assets/lyrics/treasure_ep_3/
    - assets/lyrics/treasure_ep_fin/
    - assets/lyrics/treasure_epilogue/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic

flutter_native_splash:
  color: "#000000"
  image: "assets/images/misc/splash.png"
  web: false

  android_12:
    color: "#000000"
    icon_background_color: "#000000"
    image: assets/images/misc/presplash.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
