name: ateez_lyrics
description: ATEEZ Lyrics

publish_to: "none"

version: 1.1.1+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_widget_from_html_core: ^0.14.7
  provider: ^6.0.5
  dynamic_color: ^1.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1
  test: ^1.25.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/misc/
    - assets/images/cover_art/
    - assets/lyrics/limitless/
    - assets/lyrics/spin_off_from_the_witness/
    - assets/lyrics/lookism_ost/
    - assets/lyrics/lets_get_together/
    - assets/lyrics/the_world_ep_fin_will/
    - assets/lyrics/the_world_ep_paradigm/
    - assets/lyrics/the_world_ep_1_movement/
    - assets/lyrics/the_world_ep_2_outlaw/
    - assets/lyrics/beyond_zero/
    - assets/lyrics/dont_stop/
    - assets/lyrics/fever_pt_1/
    - assets/lyrics/fever_pt_2/
    - assets/lyrics/fever_pt_3/
    - assets/lyrics/dreamers/
    - assets/lyrics/into_the_a_to_z/
    - assets/lyrics/treasure_ep_map_to_answer/
    - assets/lyrics/treasure_ep_extra_shift_the_map/
    - assets/lyrics/fever_epilogue/
    - assets/lyrics/treasure_ep_1/
    - assets/lyrics/treasure_ep_2/
    - assets/lyrics/treasure_ep_3/
    - assets/lyrics/treasure_ep_fin/
    - assets/lyrics/treasure_epilogue/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          style: normal
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-BlackItalic.ttf
          weight: 900
          style: italic

flutter_native_splash:
  color: "#262C36"
  image: "assets/images/misc/presplash.png"
  web: false

  android_12:
    color: "#262C36"
    icon_background_color: "#262C36"
    image: assets/images/misc/presplash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
